# Ansible Playbook to add circuit to Netbox
# Note: you need to export NETBOX_URL and NETBOX_TOKEN first Example:
# export NETBOX_URL=http://192.168.1.1/
# export NETBOX_token=abcde123456723456!!
---
- name: "Apply existing IP address in Netbox IPAM to a device"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Attach existing IP address to device in Netbox
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          prefix: 10.10.10.1.0/24
          assigned_object:
            name: GigabitEthernet 0/0
            device: lab-sw1
        state: present
...
