---
- name: Playbook Add IP SCP Server
  connection: network_cli
  hosts: device_roles_switch
  gather_facts: false

  tasks:
    - name: Configure SCP on Cisco Devices
      cisco.ios.ios_config:
        lines:
          - ip scp server enable
      register: print_output

    - name: Save the config
      cisco.ios.ios_config:
        save_when: modified
...
