# Note: you need to export NETBOX_URL and NETBOX_TOKEN first Example:
# export NETBOX_URL=http://192.168.1.1/
# export NETBOX_token=abcde123456723456!!
---
- name: Create VLAN Interfaces
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    data: "{{ interface }}"
    state: present    
  loop: "{{ interfaces }}"
  loop_control: 
    loop_var: interface
    label: "{{ interface['name']}}"
...